### ISSUE TITLE
Facing the issue of pickled data when using the prepare_dataset script. Can anyone help me out

### ISSUE THREAD

**Issue by Akbarmq01** [Time0o/pytorch-colorful-colorization#37]
Traceback (most recent call last):
  File "./scripts/prepare_dataset", line 13, in <module>
    from colorization.util.argparse import nice_help_formatter
  File "/home/amq/work/acclivis/project_2/pytorch-colorful-colorization/scripts/../colorization/__init__.py", line 2, in <module>
    from .modules.colorization_network import ColorizationNetwork
  File "/home/amq/work/acclivis/project_2/pytorch-colorful-colorization/scripts/../colorization/modules/colorization_network.py", line 5, in <module>
    from ..cielab import ABGamut, CIELAB, DEFAULT_CIELAB
  File "/home/amq/work/acclivis/project_2/pytorch-colorful-colorization/scripts/../colorization/cielab.py", line 214, in <module>
    DEFAULT_CIELAB = CIELAB()
  File "/home/amq/work/acclivis/project_2/pytorch-colorful-colorization/scripts/../colorization/cielab.py", line 39, in __init__
    self.gamut = gamut if gamut is not None else ABGamut()
  File "/home/amq/work/acclivis/project_2/pytorch-colorful-colorization/scripts/../colorization/cielab.py", line 18, in __init__
    self.points = np.load(self.RESOURCE_POINTS).astype(self.DTYPE)
  File "/home/amq/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 457, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False

**Comment by Time0o** [comment]
It seems like `allow_pickle` was defaulted to `False` in numpy version 1.16.3. Simply downgrading numpy should fix this (or modifying the load call to include `allow_pickle=True`).
